### ISSUE TITLE
Ghost v3, custom favicon.

### ISSUE THREAD

**Issue by VDShark** [shiva-hack/ghost-digitalocean#3]
Hello.

It looks like the custom publication icon doesn't work properly when using ghost-digitalocean storage adapter.
I didn't dive too deep, but probably the problem in the storage.

Steps to reproduce:
1) upload publication icon;
2) open the page;

The thing is - they used `/favicon.png` (or ico, depends from the extension) as URL for resolving the correct icon.
And at this address, we got 500 error ("is not stored in digital ocean").

```
Error:  is not stored in digital ocean
    at /var/lib/ghost/versions/3.0.2/node_modules/ghost-digitalocean/index.js:192:16
    at Promise._execute (/var/lib/ghost/versions/3.0.2/node_modules/ghost-digitalocean/node_modules/bluebird/js/release/debuggability.js:427:9)
    at Promise._resolveFromExecutor (/var/lib/ghost/versions/3.0.2/node_modules/ghost-digitalocean/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/lib/ghost/versions/3.0.2/node_modules/ghost-digitalocean/node_modules/bluebird/js/release/promise.js:103:10)
    at DOStore.read (/var/lib/ghost/versions/3.0.2/node_modules/ghost-digitalocean/index.js:186:12)
    at serveFavicon (/var/lib/ghost/versions/3.0.2/core/server/web/shared/middlewares/serve-favicon.js:53:22)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:275:10)
    at Object._private.redirect (/var/lib/ghost/versions/3.0.2/core/server/web/shared/middlewares/url-redirects.js:111:5)
    at urlRedirects (/var/lib/ghost/versions/3.0.2/core/server/web/shared/middlewares/url-redirects.js:119:14)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:275:10)
    at /var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:635:15
    at next (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:174:3)
    at router (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/var/lib/ghost/versions/3.0.2/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
```

Not sure, on which side is the problem.
They called the storage `read` method here
https://github.com/TryGhost/Ghost/blob/6b420d0cbd2ae6e85b1c46bb07849049da8a9223/core/server/web/shared/middlewares/serve-favicon.js#L53

**Comment by bdfeliz** [comment]
having the same problem....
